project:
  type: website

website:
  title: "Vanderbilt Biostatistics Summer Internship: Regression"
  navbar:
    left:
    - text: "Home"
      href: index.html
    - text: "Course content"
      menu:
        - text: "Class 1"
          href: class1.html
        - text: "Class 2"
          href: class2.html
        - text: "Class 3"
          href: class3.html
        - text: "Class 4"
          href: class4.html
        - text: "Class 5"
          href: class5.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true



